CREATE TABLE supplier (
    supplier_id      NUMBER
        GENERATED BY DEFAULT ON NULL AS IDENTITY,
    name             VARCHAR2(200) NOT NULL,
    address          VARCHAR2(500) NOT NULL,
    contact_number_1 VARCHAR2(200) NOT NULL,
    contact_number_2 VARCHAR2(200),
    contact_person   VARCHAR2(50) NOT NULL,
    email_address    VARCHAR2(100) NOT NULL,
    PRIMARY KEY ( supplier_id )
);

CREATE TABLE orders (
    order_id           NUMBER
        GENERATED BY DEFAULT ON NULL AS IDENTITY,
    order_ref          VARCHAR2(7) NOT NULL,
    order_date         DATE NOT NULL,
    order_total_amount NUMBER NOT NULL,
    order_description  VARCHAR2(250) NOT NULL,
    status             VARCHAR2(50) NOT NULL,
    supplier_id        NUMBER NOT NULL,
    PRIMARY KEY ( order_id ),
    CONSTRAINT fk_supplier_id FOREIGN KEY ( supplier_id )
        REFERENCES supplier ( supplier_id )
);

CREATE TABLE order_line (
    order_line_id          NUMBER
        GENERATED BY DEFAULT ON NULL AS IDENTITY,
    order_id               NUMBER NOT NULL,
    order_line_description VARCHAR2(200) NOT NULL,
    order_line_number      NUMBER NOT NULL,
    order_line_status      VARCHAR2(10) NOT NULL,
    order_line_amount      NUMBER NOT NULL,
    PRIMARY KEY ( order_line_id ),
    CONSTRAINT fk_order_id FOREIGN KEY ( order_id )
        REFERENCES orders ( order_id )
);

CREATE TABLE invoice (
    invoice_id          NUMBER
        GENERATED BY DEFAULT ON NULL AS IDENTITY,
    invoice_reference   VARCHAR2(20) NOT NULL,
    invoice_date        DATE NOT NULL,
    invoice_status      VARCHAR2(10) NOT NULL,
    invoice_hold_reason VARCHAR2(100),
    PRIMARY KEY ( invoice_id )
);

CREATE TABLE invoice_line (
    invoice_line_id     NUMBER
        GENERATED BY DEFAULT ON NULL AS IDENTITY,
    invoice_id          NUMBER NOT NULL,
    invoice_amount      NUMBER NOT NULL,
    invoice_description VARCHAR2(200),
    order_line_id       NUMBER NOT NULL,
    PRIMARY KEY ( invoice_line_id ),
    CONSTRAINT fk_order_line_id FOREIGN KEY ( order_line_id )
        REFERENCES order_line ( order_line_id ),
    CONSTRAINT fk_invoice_line_id FOREIGN KEY ( invoice_id )
        REFERENCES invoice ( invoice_id )
);

CREATE TABLE error_log (
    e_log_id          NUMBER
        GENERATED BY DEFAULT ON NULL AS IDENTITY,
    error_timestamp   TIMESTAMP NOT NULL,
    error_message     VARCHAR2(200),
    exception_message VARCHAR2(3200),
    PRIMARY KEY ( e_log_id )
);

CREATE TABLE migration_log (
    m_log_id            NUMBER
        GENERATED BY DEFAULT ON NULL AS IDENTITY,
    migration_timestamp TIMESTAMP NOT NULL,
    message             VARCHAR2(200),
    exception_message   VARCHAR2(3200),
    PRIMARY KEY ( m_log_id )
);